### ISSUE TITLE
Pressing ENTER at Address page does not submit the form

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-step-wizard#17]
1. Enter an address at "Please enter your address".
2. Press ENTER, rather than click on on the SUBMIT button

EXPECTED: Quiz to continue as the form is submitted
ACTUAL: Page is reloaded to the URL http://codeforamerica.github.io/mdc-step-wizard/? .

**Comment by phiden** [comment]
This broke, for some reason. Reopening.

**Comment by jpoles1** [comment]
I have fixed this issue, please see my pull request!
