### ISSUE TITLE
temp structures text edits

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-step-wizard#24]
![get_your_short-term_event_permit_](https://cloud.githubusercontent.com/assets/8147336/8388598/cf723392-1c18-11e5-9740-d61a0b358961.png)

**Comment by ErnieAtLYD** [comment]
Alternatively, having the text auto display and maybe having the placement here:

<img width="1229" alt="get_your_short-term_event_permit_" src="https://cloud.githubusercontent.com/assets/33945/8534975/91284c12-23f6-11e5-9e65-d984fbc099ab.png">
