### ISSUE TITLE
Consider adding city to the non-UMSA address

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-step-wizard#26]
818 NE 71st Street
"This address is not in unincorporated Miami-Dade County."

It may bring more value to say:
"This address is in Miami, and thus not in unincorporated Miami-Dade County."

**Comment by phiden** [comment]
Post geocoder, the app now tells you the full address of what was searched. I think this satisfies the additional-info aspect of this issue, so I'm closing it.
