### ISSUE TITLE
Use "You should get a special events permit instead!" (maybe?)

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-step-wizard#34]
"You need a special events permit!" - because "special events" sound so similar to "short-term" events, maybe there should be copy that says something similar to "You'll want a special events permit rather than a short-term events permit."

<img width="827" alt="get_your_short-term_event_permit_" src="https://cloud.githubusercontent.com/assets/33945/8534940/24677440-23f6-11e5-8cf3-868252e3c9b1.png">

**Comment by phiden** [comment]
I think that language is already effectively there ("you can get a more general special events permit instead of a short-term events permit."), so I'm closing this.
