### ISSUE TITLE
Should important footnotes in the middle of a process have special formatting?

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-step-wizard#36]
See the image for what I mean: 

<img width="1032" alt="get_your_short-term_event_permit_" src="https://cloud.githubusercontent.com/assets/33945/8535106/81275b90-23f7-11e5-91da-97f2243964f3.png">

Those areas emphasized are one of those footnotes where a user wouldn't want to bypass a certain step. Should there specific markup to emphasize those moments?

**Comment by phiden** [comment]
Going to put this in another more global styling issue, but the short answer is 'yes.'
