### ISSUE TITLE
Stuart's Feedback 

### ISSUE THREAD

**Issue by STKennedy** [codeforamerica/mdc-step-wizard#37]
I like the simplicity of the site and the interface, but I'm concerned you're assuming too much knowledge on the part of the user.  
- Can you provide an explanation or link to a map for what Unincorporated Miami-Dade County is?  (looks like you do this for Temporary Structures)
- Will there be links to more information about each of the needed items?  For example, I can't tell if I need a CU or where to go to get one or even for more information about it.

Do you have to have an exact address or will it search for something like the name of a park or plaza?  (I've tested the search a few times and it doesn't seem to be consistent or accurate.  My address, which is in the City, and "Pluto" showed up as being in UMSA)

I'm having a hard time testing because it seems that if you change your answer to a question the pop up path below won't change again so you're stuck with the first answer.  Or maybe it's only one path that doesn't depend on your answer above?  I'm confused.

**Comment by phiden** [comment]
issues we can work:
- explanation of UMSA
- links to more info (where we can get it, and where it's accurate)
- geolocation error catching -- and i have no idea if the API can handle the name of a park or similar . Probably?

**Comment by ErnieAtLYD** [comment]
Hey @STKennedy, thanks so much for your feedback. @phiden is going to work on some of the actionable stuff; functionality aside if the content sets of any red flags or raises concerns let us know.
