### ISSUE TITLE
Clarify UMSA with map or similar

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-step-wizard#38]

**Comment by ErnieAtLYD** [comment]
Maybe even a link to `amiinmiami`?

**Comment by phiden** [comment]
AIIM in an iFrame displays & functions but can't pass data back and forth -- making it a heavy, real-estate-chomping ornament that provides no real information.

Will embed a leaflet or similar that pins the entered location, and link to AIIM for further context.

**Comment by phiden** [comment]
Added a map & a link. Closing.
