### ISSUE TITLE
County Parks not only in UMSA

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-step-wizard#41]
if they answer no to "Is your event being held in unincorporated Miami-Dade County?" and no to "Is your event being held in a county park?", then you can trigger the "You're done" message

**Comment by phiden** [comment]
That's correct. If you're not having an event at an address in UMSA, AND you're not in a County park, then at that point you have no involvement with the county. Would it make more sense to reverse the order of those questions? @ErnieAtLYD @mathias-gibson

**Comment by mathias-gibson** [comment]
it triggers "you're done" if you say its not in UMSA, and only asks the park questions if you say you are in UMSA, but pretty sure there are county parks outside of UMSA, so yeah, I think the parks Q need to come before the UMSA Q

**Comment by phiden** [comment]
Oh, gotcha. Yeah, makes sense. This is one of those things we should also verify with the stakeholders, if we can ever get their attention!
