### ISSUE TITLE
Christmas Trees, Pumpkins and Sparklers

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-step-wizard#44]
should pumpkins be in here if the reason for this button is to remind them to check the "MDFR safety inspection checklist for selling Christmas trees or sparklers"

![get_your_short-term_event_permit_](https://cloud.githubusercontent.com/assets/8147336/8602810/3d941b1e-2629-11e5-9f57-2d0f01f5756c.png)

**Comment by phiden** [comment]
According to the currently available information, yes. Closing the issue but let's raise the flag with the stakeholders.

**Comment by mathias-gibson** [comment]
there are a long list of requirements for xmas trees and sparklers individually, we should split them out

**Comment by mathias-gibson** [comment]
also, pumpkins dont have their own special requirements, so we should take them out of that list of event types

**Comment by phiden** [comment]
@mathias-gibson I'd agree with you, except that that's in the current official language as a thing that gets specifically called out. @ErnieAtLYD what do you think?

**Comment by mathias-gibson** [comment]
whats so official about the language? I havent seen any mention of a
relation between these items other than being things that are often sold
during short term events, possibly just a mistake/misinterpretation, esp
since their are no separate requirements associated with pumpkins that have
been noted anywhere

**Comment by phiden** [comment]
Copy that.
