### ISSUE TITLE
List of Requirements for Sparklers (Event Types)

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-step-wizard#47]
Separate sparklers into its own button on event types, and show this list of requirements when they click the button (from http://www.miamidade.gov/permits/short-term-sparklers.asp):
Sparkler sales can only be conducted on property zoned BU (Business District).
Applications for the building permit must be submitted at least 14 days prior to the date the sparkler sales will commence.
Site drawing identifying parking spaces.
Written approval from Miami-Dade Health Department at 1725 NW 167th Street, 305-623-3500.
Executed agreement between the property owner and the sparkler retailer, giving permission to use the property for the sale of sparklers and the dates of operation.
Application is to include a copy of the Certificate of Registration available from State Fire Marshal 850-413-3170.
Copy of the company owner's Florida Driver's License.
Site drawing identifying proximity of all buildings, other structures and streets and indicating location and type of fire extinguishers.
Fire watch will be required if tent exceeds 1,600 sq. ft. or if distance separation to buildings is less than 100 feet. Tents are to be at least 25 feet from street and 30 feet from property lines. A Fire Department inspector will make a final determination.
Provide dates and hours of operation.
Provide a minimum of two approved fire extinguishers rated 2A10BC to be readily visible and placed near exits.
Travel distance to extinguishers is not to exceed 75 feet.
There shall be no smoking in tents, and appropriate "No Smoking" signs shall be displayed conspicuously.
Sparklers shall be sold in packages or zip locked or tied polyethylene bags.
Sales from motor vehicles are prohibited.
Sparklers shall not be stored, sold or dispensed in any manner where combustibles or flammable materials are dispensed.
Sparklers shall be stored on skids or pallets a minimum of 4" off the ground to protect the chemical stability of the compounds from moisture.
All merchandise must be removed from the tent daily unless an approved security system is provided.
All storage containers shall be labeled "Class C Explosives" or "Explosives 1.4G".

**Comment by phiden** [comment]
Added.
