### ISSUE TITLE
List of requirements for xmas trees (event types)

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-step-wizard#48]
Separate xmas trees into its own button on event types, and show this list of requirements when they click the button (http://www.miamidade.gov/permits/short-term-christmas-trees.asp):

Christmas tree sales can only be conducted on properties zoned BU (Business District). - http://www.miamidade.gov/zoning/districts.asp
Application for the building permit must be submitted at least fourteen days prior to the date the Christmas tree sales will commence.
Written approval from Miami-Dade Health Department at 1725 NW 167th Street, 305-623-3500.
Executed agreement between the property owner and the Christmas tree retailer, giving permission to use the property for the sale of Christmas trees and the dates of operation.
Minimum head room 7'6"
The following must be provided in order to comply with the Florida Fire Prevention Code:
Provide one ABC type "2A” fire extinguisher for each 400 sq. ft., where mounted top of the extinguisher does not exceed five feet above floor. After the first 1,200 sq. ft. (three extinguishers), provide one additional extinguisher for each 1,000 sq. ft.
Minimum aisle width with seating 44". Aisles serving areas other than seating shall not be less than five feet wide and the number of such aisles shall be at the discretion of the authority having jurisdiction.
No parking within 20 feet except upon a public street.
"No Smoking" signs
Provide flame spread (class A) affidavit of affirmation for membrane structures.
There shall be a minimum of 12 feet between stake lines (multiple tents).
No unauthorized open flames permitted in tents.
Heating devices must comply with NFPA 102, and the authority having jurisdiction.

**Comment by phiden** [comment]
Done.
