### ISSUE TITLE
Add a description of a STEP on the home page

### ISSUE THREAD

**Issue by julianbonilla** [codeforamerica/mdc-step-wizard#59]
Not clear from the home page what a STEP is and why I might need one.  Possibly link to or include the description from: http://www.miamidade.gov/permits/short-term-events.asp

> Any event that lasts 45 days or less where temporary structures and facilities are required is a Short Term Event. These events can be for revivals, carnivals, assemblies, circuses, sporting tournaments and for the sale of items such as sparklers, Christmas trees, pumpkins, stuffed animals and/or flowers.

**Comment by phiden** [comment]
Added.

**Comment by ErnieAtLYD** [comment]
Thanks Julian :)
