### ISSUE TITLE
Replace inline `http://` with just `://`

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-step-wizard#63]
Best practices say to replace `src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"` with just `src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"`. This will prevent any JS errors (which would crash the wizard) if someone tried to access the URL with an https protocol.

**Comment by phiden** [comment]
That particular practice breaks my localhost, making this a PITA to work on. Instead swapped for httpS, which is accepted practice as well.  When this moves off testing, we can remove the https altogether.
