### ISSUE TITLE
Replace copy in site "A temporary structure is defined as x, y, z." with new copy

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-step-wizard#67]
Replace the following string in the wizard: "A temporary structure is defined as x, y, z." with the following:

"A temporary structure includes tents (also called a "membrane structure") above a 10' x 12' threshold, bleachers, stages, specialty wiring, rides, lifts, and ramps, non-portable ventilation systems or enclosed cooking facilities."

**Comment by jpoles1** [comment]
I can fix this.

**Comment by jpoles1** [comment]
Fixed in pull request #68
