### ISSUE TITLE
Add Google analytics

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-step-wizard#76]

**Comment by phiden** [comment]
@mathias-gibson can you get me the code for this, please?

**Comment by mathias-gibson** [comment]
wait, is this for adding it to the dashboard as tracking or as a metric panel? I already made a pull request and added it to the dashboard, and @ErnieAtLYD merged it

**Comment by phiden** [comment]
This is for the STEP wizard, not the dashboard.

**Comment by mathias-gibson** [comment]
ah, got it, here you go:

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-20825280-31', 'auto');
  ga('send', 'pageview');
</script>

**Comment by phiden** [comment]
oh, nevermind. hidden in the jump.
